In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [5]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]


arr1=np.array([lst1,lst2,lst3])

In [6]:
arr1.shape

(3, 5)

In [7]:
#indesing

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
arr[3]

4

In [10]:
arr[3]=5

In [11]:
arr

array([1, 2, 3, 5])

In [12]:
arr[1:]

array([2, 3, 5])

In [13]:
arr[-1]

5

In [14]:
arr[:-1]

array([1, 2, 3])

In [15]:
arr[::]

array([1, 2, 3, 5])

In [16]:
arr[::-1]

array([5, 3, 2, 1])

In [17]:
arr[::-2]

array([5, 2])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [19]:
arr1[:,1]

array([2, 3, 4])

In [20]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [21]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [22]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [23]:
arr1[:,::3]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
arr1[:,::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [25]:
#EDA

In [26]:
arr

array([1, 2, 3, 5])

In [27]:
arr<2

array([ True, False, False, False])

In [28]:
arr[arr<2]

array([1])

In [29]:
arr1.shape

(3, 5)

In [30]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [31]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [32]:
##Mechanism to create an array

In [33]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [34]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [36]:
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [37]:
arr*arr

array([ 1,  4,  9, 25])

In [38]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [39]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [40]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [41]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.random.randint(10,50,4)

array([15, 40, 32, 26])

In [44]:
np.random.randint(10,50,4).reshape(2,2)

array([[33, 20],
       [49, 13]])

In [45]:
#normal distribution

np.random.randn(5,6)

array([[ 0.60342111, -1.03893049,  2.34062327,  1.77802358,  1.66291465,
         0.43146565],
       [-0.06942919,  0.66989078, -1.02164339, -0.38349283, -0.09633245,
        -1.1178406 ],
       [ 0.34971349, -0.37543943,  0.91349246,  1.03984833,  0.87334329,
        -1.76303437],
       [-0.23811451, -0.66852708,  1.56155197, -0.20403763,  1.54925032,
        -0.33399046],
       [-0.57055994,  0.37078524,  2.06423964,  0.7415218 , -1.2576811 ,
        -0.3848419 ]])